### ISSUE TITLE
Move margin notes to the left margin or right margin based on space and linked text position

### ISSUE THREAD

**Issue by sirinath** [capnfabs/paperesque#5]
Based on space and whether the margin link is towards the left can some of the margin notes move to the left? Similarly to the right, as you already have.

**Comment by capnfabs** [comment]
Hey @sirinath, I'm reluctant to move margin notes to the left, because people reading left-to-right languages tend to read the stuff on the left first. I think it could be distracting to have to visually 'skip over' a margin note to get to the content, whereas you don't have to do that when they're on the right.

If you want to make the change to your own instance of the theme, you're welcome to -- the relevant code is in [`floatingFootnotes.js`](https://github.com/capnfabs/paperesque/blob/master/js/floatingFootnotes.js) and the JS build instructions are here: https://github.com/capnfabs/paperesque#hacking--modifying-the-theme

All the best
-- Fabian
