### ISSUE TITLE
Change banner image

### ISSUE THREAD

**Issue by pmeiners** [capnfabs/paperesque#9]
It might be a good idea to add an explanation how to change the background banner to the https://themes.gohugo.io/paperesque/ tutorial.

**Comment by capnfabs** [comment]
Hi @pmeiners ! Do you mean the blue / orange stripe across the top of the page?

The best way to do that is by modifying the CSS; there's two examples of people who've done that here:

- Astronomia e Astrofísica - [Github](https://github.com/luanguimaraesla/astro-site), [Site](https://astro.l2n.me/) (I really like this effect with the background image)
- James Liu - [Github](https://github.com/disposedtrolley/blog), [Site](http://jamesliu.io/)

I'm not going to add a tutorial for this because it's more a standard HTML/CSS development task than something related to this specific theme, but you probably want to look at modifying the `.nav-bkg` class in `styles.css`.
